version: '3.9'

services:
  reverse-proxy:
    image: traefik:v2.4
    volumes: 
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - letsencrypt:/letsencrypt
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.docker.network=traefik-public
      - traefik.enable=true

      - traefik.http.services.dashboard.loadbalancer.server.port=8080
      - traefik.http.routers.dashboard.service=api@internal

      - traefik.http.routers.dashboard.rule=Host(`dashboard.localhost`)
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.tls.certresolver=le

      - traefik.http.middlewares.auth.basicauth.users=${AUTH_USERNAME}:${AUTH_PASSWORD}
      - traefik.http.routers.dashboard.middlewares=auth
    command: 
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443

      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=${LE_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json

      - --api.insecure=true
      - --api.dashboard=true
      - --log.level=DEBUG
      - --log.filePath=/var/log/traefik/system.log
      - --accesslog=true
      - --accesslog.filePath=/var/log/traefik/access.log
    networks: 
      - traefik-public
    restart: always

volumes: 
  letsencrypt:

networks:
  traefik-public:
    external: true
