version: "3.9"

services:
  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: ${DBMS_USER}
      POSTGRES_PASSWORD: ${DBMS_PASSWORD}
      POSTGRES_DB: ${DBMS_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal
    restart: always

  backend:
    build: ./backend
    environment:
      FASTIFY_ADDRESS: 0.0.0.0
      FASTIFY_PORT: 8080
    ports:
      - 8080:8080
    networks:
      - internal
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    ports:
      - 3000:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`${APP_HOST}`)
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=le
      - traefik.port=80
    networks:
      - traefik-public
      - internal
    restart: always

volumes:
  pg_data:

networks:
  traefik-public:
    external: true
  internal:
    external: false
