name: Build dockerized Node.js app

on:
  pull_request:
    branches: 
      - master
      - develop
  push:
    branches: 
      - develop
      
env:
  DBMS_USER: ${{ secrets.DBMS_USER }}
  DBMS_PASSWORD: ${{ secrets.DBMS_PASSWORD }}
  DBMS_DB: ${{ secrets.DBMS_DB }}
  BACKEND_HOST: ${{ secrets.BACKEND_HOST }}
  BACKEND_PORT: ${{ secrets.BACKEND_PORT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack using cache
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          compose_file: docker-compose.yml
      - name: Up and build the docker-compose stack
        run: docker-compose up -d --build
